import type {
  Player,
  LeaderboardEntry,
  PlayerScorecard,
  PlayerStatistics,
  PlayerProfile,
} from "./types";

const players: Player[] = [
  {
    id: "28237",
    firstName: "Rory",
    lastName: "McIlroy",
    country: "Northern Ireland",
    countryCode: "NIR",
    age: 35,
    height: "5' 9\"",
    weight: "160 lbs",
    worldRanking: 2,
    bio: "Rory McIlroy is a professional golfer from Northern Ireland who is a member of both the European and PGA Tours. He is a four-time major champion, winning the 2011 U.S. Open, 2012 PGA Championship, 2014 Open Championship, and 2014 PGA Championship. He has spent over 100 weeks as world number one.",
  },
  {
    id: "30925",
    firstName: "Dustin",
    lastName: "Johnson",
    country: "United States",
    countryCode: "USA",
    age: 39,
    height: "6' 4\"",
    weight: "190 lbs",
    worldRanking: 12,
    bio: "Dustin Johnson is an American professional golfer who plays on the PGA Tour. He has won two major championships, the 2016 U.S. Open and the 2020 Masters Tournament. He is known for his prodigious driving distance and athleticism.",
  },
  {
    id: "34046",
    firstName: "Jordan",
    lastName: "Spieth",
    country: "United States",
    countryCode: "USA",
    age: 30,
    height: "6' 1\"",
    weight: "175 lbs",
    worldRanking: 18,
    bio: "Jordan Spieth is an American professional golfer on the PGA Tour and former world number one in the Official World Golf Ranking. He is a three-time major winner and the 2015 FedEx Cup champion.",
  },
  {
    id: "35891",
    firstName: "Scottie",
    lastName: "Scheffler",
    country: "United States",
    countryCode: "USA",
    age: 27,
    height: "6' 3\"",
    weight: "200 lbs",
    worldRanking: 1,
    bio: "Scottie Scheffler is an American professional golfer who plays on the PGA Tour. He is the 2022 Masters Tournament champion and has been ranked world number one. Known for his consistent ball-striking and clutch putting.",
  },
  {
    id: "39977",
    firstName: "Max",
    lastName: "Homa",
    country: "United States",
    countryCode: "USA",
    age: 33,
    height: "6' 1\"",
    weight: "180 lbs",
    worldRanking: 9,
    bio: "Max Homa is an American professional golfer who plays on the PGA Tour. Known for his social media presence and sharp wit, Homa has multiple PGA Tour victories and has represented the United States in international competitions.",
  },
  {
    id: "40098",
    firstName: "Patrick",
    lastName: "Cantlay",
    country: "United States",
    countryCode: "USA",
    age: 32,
    height: "6' 1\"",
    weight: "170 lbs",
    worldRanking: 5,
    bio: "Patrick Cantlay is an American professional golfer who plays on the PGA Tour. He was the number one golfer in the World Amateur Golf Ranking for a record 55 weeks. He has multiple PGA Tour wins including the 2021 FedEx Cup.",
  },
  {
    id: "45791",
    firstName: "Xander",
    lastName: "Schauffele",
    country: "United States",
    countryCode: "USA",
    age: 30,
    height: "5' 10\"",
    weight: "175 lbs",
    worldRanking: 3,
    bio: "Xander Schauffele is an American professional golfer. He is an Olympic gold medalist and has multiple PGA Tour wins. Known for his consistency and ability to perform in major championships.",
  },
  {
    id: "46046",
    firstName: "Scottie",
    lastName: "Scheffler",
    country: "United States",
    countryCode: "USA",
    age: 27,
    height: "6' 3\"",
    weight: "200 lbs",
    worldRanking: 1,
    bio: "Scottie Scheffler is an American professional golfer who plays on the PGA Tour. He is the 2022 Masters Tournament champion and has been ranked world number one.",
  },
  {
    id: "47483",
    firstName: "Will",
    lastName: "Zalatoris",
    country: "United States",
    countryCode: "USA",
    age: 27,
    height: "6' 2\"",
    weight: "175 lbs",
    worldRanking: 24,
    bio: "Will Zalatoris is an American professional golfer who plays on the PGA Tour. He gained prominence with his runner-up finish at the 2021 Masters Tournament in his debut.",
  },
  {
    id: "48081",
    firstName: "Viktor",
    lastName: "Hovland",
    country: "Norway",
    countryCode: "NOR",
    age: 26,
    height: "5' 10\"",
    weight: "165 lbs",
    worldRanking: 4,
    bio: "Viktor Hovland is a Norwegian professional golfer who plays on the PGA Tour. He was the first Norwegian to win on the PGA Tour and has multiple worldwide victories.",
  },
  {
    id: "50525",
    firstName: "Collin",
    lastName: "Morikawa",
    country: "United States",
    countryCode: "USA",
    age: 27,
    height: "5' 9\"",
    weight: "160 lbs",
    worldRanking: 6,
    bio: "Collin Morikawa is an American professional golfer who plays on the PGA Tour. He is a two-time major champion, winning the 2020 PGA Championship and the 2021 Open Championship.",
  },
  {
    id: "52955",
    firstName: "Ludvig",
    lastName: "Åberg",
    country: "Sweden",
    countryCode: "SWE",
    age: 24,
    height: "6' 3\"",
    weight: "190 lbs",
    worldRanking: 7,
    bio: "Ludvig Åberg is a Swedish professional golfer. He was the number one ranked amateur in the world before turning professional and has quickly risen through the professional ranks.",
  },
  {
    id: "55182",
    firstName: "Wyndham",
    lastName: "Clark",
    country: "United States",
    countryCode: "USA",
    age: 30,
    height: "6' 0\"",
    weight: "175 lbs",
    worldRanking: 8,
    bio: "Wyndham Clark is an American professional golfer who plays on the PGA Tour. He won his first major championship at the 2023 U.S. Open at Los Angeles Country Club.",
  },
  {
    id: "57366",
    firstName: "Cameron",
    lastName: "Young",
    country: "United States",
    countryCode: "USA",
    age: 27,
    height: "6' 3\"",
    weight: "185 lbs",
    worldRanking: 15,
    bio: "Cameron Young is an American professional golfer on the PGA Tour. He was named PGA Tour Rookie of the Year in 2022 and has multiple runner-up finishes in major championships.",
  },
  {
    id: "59866",
    firstName: "Sahith",
    lastName: "Theegala",
    country: "United States",
    countryCode: "USA",
    age: 26,
    height: "6' 2\"",
    weight: "185 lbs",
    worldRanking: 19,
    bio: "Sahith Theegala is an American professional golfer who plays on the PGA Tour. He was a three-time NCAA All-American at Pepperdine University.",
  },
];

const leaderboard: LeaderboardEntry[] = [
  {
    position: "1",
    playerId: "35891",
    playerName: "Scheffler, S.",
    countryCode: "USA",
    total: 276,
    toPar: -12,
    round1: 68,
    round2: 69,
    round3: 70,
    round4: 69,
    thru: "F",
  },
  {
    position: "2",
    playerId: "28237",
    playerName: "McIlroy, R.",
    countryCode: "NIR",
    total: 278,
    toPar: -10,
    round1: 69,
    round2: 70,
    round3: 68,
    round4: 71,
    thru: "F",
  },
  {
    position: "3",
    playerId: "45791",
    playerName: "Schauffele, X.",
    countryCode: "USA",
    total: 279,
    toPar: -9,
    round1: 70,
    round2: 68,
    round3: 71,
    round4: 70,
    thru: "F",
  },
  {
    position: "4",
    playerId: "50525",
    playerName: "Morikawa, C.",
    countryCode: "USA",
    total: 280,
    toPar: -8,
    round1: 71,
    round2: 69,
    round3: 70,
    round4: 70,
    thru: "F",
  },
  {
    position: "T5",
    playerId: "48081",
    playerName: "Hovland, V.",
    countryCode: "NOR",
    total: 281,
    toPar: -7,
    round1: 69,
    round2: 71,
    round3: 70,
    round4: 71,
    thru: "F",
  },
  {
    position: "T5",
    playerId: "52955",
    playerName: "Åberg, L.",
    countryCode: "SWE",
    total: 281,
    toPar: -7,
    round1: 70,
    round2: 70,
    round3: 71,
    round4: 70,
    thru: "F",
  },
  {
    position: "7",
    playerId: "40098",
    playerName: "Cantlay, P.",
    countryCode: "USA",
    total: 282,
    toPar: -6,
    round1: 71,
    round2: 70,
    round3: 71,
    round4: 70,
    thru: "F",
  },
  {
    position: "T8",
    playerId: "34046",
    playerName: "Spieth, J.",
    countryCode: "USA",
    total: 283,
    toPar: -5,
    round1: 72,
    round2: 69,
    round3: 72,
    round4: 70,
    thru: "F",
  },
  {
    position: "T8",
    playerId: "55182",
    playerName: "Clark, W.",
    countryCode: "USA",
    total: 283,
    toPar: -5,
    round1: 70,
    round2: 72,
    round3: 69,
    round4: 72,
    thru: "F",
  },
  {
    position: "T10",
    playerId: "30925",
    playerName: "Johnson, D.",
    countryCode: "USA",
    total: 284,
    toPar: -4,
    round1: 71,
    round2: 71,
    round3: 71,
    round4: 71,
    thru: "F",
  },
  {
    position: "T10",
    playerId: "57366",
    playerName: "Young, C.",
    countryCode: "USA",
    total: 284,
    toPar: -4,
    round1: 72,
    round2: 70,
    round3: 71,
    round4: 71,
    thru: "F",
  },
  {
    position: "12",
    playerId: "47483",
    playerName: "Zalatoris, W.",
    countryCode: "USA",
    total: 285,
    toPar: -3,
    round1: 73,
    round2: 70,
    round3: 72,
    round4: 70,
    thru: "F",
  },
  {
    position: "T13",
    playerId: "39977",
    playerName: "Homa, M.",
    countryCode: "USA",
    total: 286,
    toPar: -2,
    round1: 72,
    round2: 72,
    round3: 70,
    round4: 72,
    thru: "F",
  },
  {
    position: "T13",
    playerId: "59866",
    playerName: "Theegala, S.",
    countryCode: "USA",
    total: 286,
    toPar: -2,
    round1: 71,
    round2: 73,
    round3: 71,
    round4: 71,
    thru: "F",
  },
  {
    position: "15",
    playerId: "46046",
    playerName: "Scheffler, S.",
    countryCode: "USA",
    total: 288,
    toPar: 0,
    round1: 73,
    round2: 72,
    round3: 72,
    round4: 71,
    thru: "F",
  },
];

function generateRound(
  scores: number[],
  par: number[]
): { hole: number; par: number; score: number; yards: number }[] {
  const yards = [
    445, 575, 350, 240, 495, 180, 450, 570, 460, 495, 520, 155, 510, 440, 530, 170, 440, 465,
  ];
  return scores.map((score, i) => ({
    hole: i + 1,
    par: par[i] ?? 4,
    score,
    yards: yards[i] ?? 400,
  }));
}

const augustaPar = [4, 5, 4, 3, 4, 3, 4, 5, 4, 4, 4, 3, 5, 4, 5, 3, 4, 4];

const scorecards: PlayerScorecard[] = [
  {
    playerId: "28237",
    rounds: [
      {
        roundNumber: 1,
        scores: generateRound([4, 4, 4, 3, 4, 3, 4, 5, 4, 4, 4, 3, 5, 4, 5, 2, 4, 4], augustaPar),
        total: 69,
        toPar: -3,
      },
      {
        roundNumber: 2,
        scores: generateRound([4, 5, 4, 3, 4, 3, 4, 5, 4, 4, 4, 3, 4, 4, 5, 3, 4, 4], augustaPar),
        total: 70,
        toPar: -2,
      },
      {
        roundNumber: 3,
        scores: generateRound([4, 4, 4, 2, 4, 3, 4, 4, 4, 4, 4, 3, 5, 4, 5, 3, 4, 4], augustaPar),
        total: 68,
        toPar: -4,
      },
      {
        roundNumber: 4,
        scores: generateRound([4, 5, 4, 3, 4, 3, 4, 5, 4, 4, 4, 3, 5, 4, 5, 3, 5, 4], augustaPar),
        total: 71,
        toPar: -1,
      },
    ],
  },
  {
    playerId: "35891",
    rounds: [
      {
        roundNumber: 1,
        scores: generateRound([4, 4, 4, 3, 4, 3, 4, 5, 4, 4, 4, 3, 5, 4, 4, 3, 4, 4], augustaPar),
        total: 68,
        toPar: -4,
      },
      {
        roundNumber: 2,
        scores: generateRound([4, 5, 4, 3, 4, 3, 4, 5, 4, 4, 4, 3, 5, 4, 5, 3, 4, 4], augustaPar),
        total: 69,
        toPar: -3,
      },
      {
        roundNumber: 3,
        scores: generateRound([4, 5, 4, 3, 4, 3, 4, 5, 4, 4, 4, 3, 5, 4, 5, 3, 5, 4], augustaPar),
        total: 70,
        toPar: -2,
      },
      {
        roundNumber: 4,
        scores: generateRound([4, 4, 4, 3, 4, 3, 4, 5, 4, 4, 4, 3, 5, 4, 5, 3, 4, 4], augustaPar),
        total: 69,
        toPar: -3,
      },
    ],
  },
];

const statistics: PlayerStatistics[] = [
  {
    playerId: "28237",
    stats: [
      { category: "Strokes Gained: Total", value: "2.342", rank: "3rd" },
      { category: "Strokes Gained: Off-the-Tee", value: "0.892", rank: "5th" },
      { category: "Strokes Gained: Approach", value: "0.745", rank: "8th" },
      { category: "Strokes Gained: Around-the-Green", value: "0.312", rank: "12th" },
      { category: "Strokes Gained: Putting", value: "0.393", rank: "15th" },
      { category: "Driving Distance", value: "312.4 yds", rank: "18th" },
      { category: "Fairways in Regulation", value: "68.2%", rank: "22nd" },
      { category: "Greens in Regulation", value: "75.0%", rank: "6th" },
      { category: "Putting Average", value: "1.72", rank: "24th" },
      { category: "Scoring Average", value: "69.50", rank: "2nd" },
    ],
  },
  {
    playerId: "35891",
    stats: [
      { category: "Strokes Gained: Total", value: "2.891", rank: "1st" },
      { category: "Strokes Gained: Off-the-Tee", value: "1.124", rank: "2nd" },
      { category: "Strokes Gained: Approach", value: "0.982", rank: "3rd" },
      { category: "Strokes Gained: Around-the-Green", value: "0.445", rank: "6th" },
      { category: "Strokes Gained: Putting", value: "0.340", rank: "18th" },
      { category: "Driving Distance", value: "298.7 yds", rank: "35th" },
      { category: "Fairways in Regulation", value: "72.7%", rank: "8th" },
      { category: "Greens in Regulation", value: "79.2%", rank: "2nd" },
      { category: "Putting Average", value: "1.65", rank: "12th" },
      { category: "Scoring Average", value: "69.00", rank: "1st" },
    ],
  },
];

const profiles: PlayerProfile[] = [
  {
    player: players.find((p) => p.id === "28237")!,
    pastResults: [
      { year: 2024, position: "T22", score: "289", toPar: "+1" },
      { year: 2023, position: "T7", score: "283", toPar: "-5" },
      { year: 2022, position: "2", score: "278", toPar: "-10" },
      { year: 2021, position: "T18", score: "287", toPar: "-1" },
      { year: 2020, position: "T5", score: "282", toPar: "-6" },
      { year: 2019, position: "T21", score: "288", toPar: "E" },
      { year: 2018, position: "T5", score: "279", toPar: "-9" },
      { year: 2015, position: "4", score: "276", toPar: "-12" },
      { year: 2014, position: "T8", score: "284", toPar: "-4" },
      { year: 2011, position: "T20", score: "286", toPar: "-2" },
    ],
  },
  {
    player: players.find((p) => p.id === "35891")!,
    pastResults: [
      { year: 2024, position: "1", score: "276", toPar: "-12" },
      { year: 2023, position: "T10", score: "283", toPar: "-5" },
      { year: 2022, position: "1", score: "278", toPar: "-10" },
    ],
  },
];

export function getAllPlayers(): Player[] {
  return players;
}

export function getPlayerById(id: string): Player | undefined {
  return players.find((p) => p.id === id);
}

export function getLeaderboard(): LeaderboardEntry[] {
  return leaderboard;
}

export function getScorecard(playerId: string): PlayerScorecard | undefined {
  return scorecards.find((s) => s.playerId === playerId);
}

export function getStatistics(playerId: string): PlayerStatistics | undefined {
  return statistics.find((s) => s.playerId === playerId);
}

export function getPlayerProfile(playerId: string): PlayerProfile | undefined {
  return profiles.find((p) => p.player.id === playerId);
}
